### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by papermoon1978** [atom-minimap/minimap-find-and-replace#5]
Hmm, I am sure the minimap find an replace binding worked quite well in the past, but today I noticed that I don't see results highlighted in the minimap anymore. Yesterday I updated all my packages, so maybe it has something to do with it. The find and replace binding is still enabled in the minimap settings.

minimap 4.3.1 bindings: 4.2.0 atom: 182

**Comment by abe33** [comment]
Ok, I see, starting with 4.2.0 this plugin use the service provider introduced in minimap 4.4.0, you're using minimap 4.3.1 which doesn't have the service provider yet. 

You probably haven't seen the update for the minimap because the min engine was bump to 0.184. I should have updated the plugin's engine version as well to avoid this kind of problem. 

If you can, the best course of action would be to update Atom to v0.184 so that you can get the latest minimap update.

Sorry for the inconvenience, let me know if you have any issue regarding the update.

**Comment by papermoon1978** [comment]
Thanks for the fast response. atom currently doesn't show me 0.184 (but when I remember correctly I've read something about update issues every now and then) so I'll wait. Again ... thanks for your explanation :-)

**Comment by abe33** [comment]
You can still downgrade the plugin version by uninstalling it and then reinstalling it with `apm install minimap-find-and-replace@4.1.0`.

**Comment by papermoon1978** [comment]
version 4.1 works fine. Thanks for the tip :-)

**Comment by papermoon1978** [comment]
Just upgraded to atom 186, minimap 4.5.0 and find and replace binding 4.2.0. Works also fine. I guess this can be closed.

**Comment by abe33** [comment]
Thanks for the follow up, I close it then.
